customhost = "employee.ck9hrfiye8hq.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "teoshanwynn-employee"
customregion = "us-east-1"
